//
//  DetailBreedInteractorTests.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsApiCleanSwiftExample
import XCTest

class DetailBreedInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: DetailBreedInteractor!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupDetailBreedInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupDetailBreedInteractor() {
        sut = DetailBreedInteractor()
    }

    // MARK: Test doubles

    class DetailBreedPresentationLogicSpy: DetailBreedPresentationLogic {
        var presentSomethingCalled = false

        func presentSomething(response: DetailBreed.Something.Response) {
            presentSomethingCalled = true
        }
    }

    // MARK: Tests

    func testDoSomething() {
        // Given
        let spy = DetailBreedPresentationLogicSpy()
        sut.presenter = spy
        let request = DetailBreed.Something.Request()

        // When
        sut.doSomething(request: request)

        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
