//
//  DetailBreedWorkerTests.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsApiCleanSwiftExample
import XCTest

class DetailBreedWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: DetailBreedWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupDetailBreedWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupDetailBreedWorker() {
        sut = DetailBreedWorker()
    }

    // MARK: Test doubles

    // MARK: Tests

    func testAPI() {
        // NOTE:
        // we should use some kind of interceptors for the network stubs to test this.
    }
}
