//
//  DetailBreedPresenterTests.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsApiCleanSwiftExample
import XCTest

class DetailBreedPresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: DetailBreedPresenter!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupDetailBreedPresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupDetailBreedPresenter() {
        sut = DetailBreedPresenter()
    }

    // MARK: Test doubles

    class DetailBreedDisplayLogicSpy: DetailBreedDisplayLogic {
        var displayPicturesCalled = false

        func displayPictures(viewModel: DetailBreed.InitialLoad.ViewModel) {
            displayPicturesCalled = true
        }
    }

    // MARK: Tests

    func testPresentSomething() {
        // Given
        let spy = DetailBreedDisplayLogicSpy()
        sut.viewController = spy
        let response = DetailBreed.InitialLoad.Response(pictures: ["pic1", "pic2"], title: "Bulldog")

        // When
        sut.presentPictures(response: response)

        // Then
        XCTAssertTrue(spy.displayPicturesCalled, "presentPictures(response:) should ask the view controller to display the pictures")
    }
}
