//
//  ListBreedsInteractorTests.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsApiCleanSwiftExample
import XCTest

class ListBreedsInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: ListBreedsInteractor!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupListBreedsInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupListBreedsInteractor() {
        sut = ListBreedsInteractor()
    }

    // MARK: Test doubles

    class ListBreedsPresentationLogicSpy: ListBreedsPresentationLogic {
        var presentSomethingCalled = false

        func presentSomething(response: ListBreeds.Something.Response) {
            presentSomethingCalled = true
        }
    }

    // MARK: Tests

    func testDoSomething() {
        // Given
        let spy = ListBreedsPresentationLogicSpy()
        sut.presenter = spy
        let request = ListBreeds.Something.Request()

        // When
        sut.doSomething(request: request)

        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
