//
//  ListBreedsViewControllerTests.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsApiCleanSwiftExample
import XCTest

class ListBreedsViewControllerTests: XCTestCase {
    // MARK: Subject under test
    var sut: ListBreedsViewController!
    var window: UIWindow!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupListBreedsViewController()
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: Test setup
    
    func setupListBreedsViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "ListBreedsViewController") as! ListBreedsViewController
    }

    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }

    // MARK: Test doubles

    class ListBreedsBusinessLogicSpy: ListBreedsBusinessLogic {
        var initialLoadCalled = false
        var selectCalled = false

        func initialLoad(request: ListBreeds.InitialLoad.Request) {
            initialLoadCalled = true
        }

        func select(row: Int) {
            selectCalled = true
        }
    }

    func testShouldInitialLoadWhenViewIsLoaded() {
        // Given
        let spy = ListBreedsBusinessLogicSpy()
        sut.interactor = spy

        // When
        loadView()

        // Then
        XCTAssertTrue(spy.initialLoadCalled, "viewDidLoad() should ask the interactor to do initialLoad()")
    }

    func testDisplayBreeds() {
        // Given
        let viewModel = ListBreeds.InitialLoad.ViewModel(breeds: ["boxer", "pekines"])

        // When
        loadView()
        sut.displayBreeds(viewModel: viewModel)

        // Then
        XCTAssertEqual(sut.viewModel?.breeds.count, viewModel.breeds.count, "displayBreeds(viewModel:) should be the same")
    }
}
