//
//  ListBreedsWorkerTests.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogsApiCleanSwiftExample
import XCTest

class ListBreedsWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: ListBreedsWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupListBreedsWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupListBreedsWorker() {
        sut = ListBreedsWorker()
    }

    // MARK: Test doubles

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}
