//
//  ListBreedsInteractor.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBreedsBusinessLogic {
    func initialLoad(request: ListBreeds.InitialLoad.Request)
    func select(row: Int)
}

protocol ListBreedsDataStore {
    var selectedBreed: String? { get set }
}

class ListBreedsInteractor: ListBreedsBusinessLogic, ListBreedsDataStore {

    var presenter: ListBreedsPresentationLogic?
    var worker: ListBreedsWorkerProtocol = ListBreedsWorker()
    var selectedBreed: String?

    //internal
    var breeds:[String] = []

    func initialLoad(request: ListBreeds.InitialLoad.Request) {
        worker.listAllBreeds(completion: { (apiResponse, error) in
            var response = ListBreeds.InitialLoad.Response(breeds: [])
            if let apiResponse = apiResponse {
                self.breeds = apiResponse.message
                response = ListBreeds.InitialLoad.Response(breeds: self.breeds)
            }
            self.presenter?.presentListBreeds(response: response)
        })
    }

    func select(row: Int) {
        selectedBreed = breeds[row]
        presenter?.presentDetailBreed()
    }

}
