//
//  ListBreedsPresenter.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBreedsPresentationLogic {
    func presentSomething(response: ListBreeds.Something.Response)
}

class ListBreedsPresenter: ListBreedsPresentationLogic {
    weak var viewController: ListBreedsDisplayLogic?

    // MARK: Do something

    func presentSomething(response: ListBreeds.Something.Response) {
        let viewModel = ListBreeds.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
