//
//  ListBreedsInteractor.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBreedsBusinessLogic {
    func initialLoad(request: ListBreeds.InitialLoad.Request)
}

protocol ListBreedsDataStore {
    //var name: String { get set }
}

class ListBreedsInteractor: ListBreedsBusinessLogic, ListBreedsDataStore {
    var presenter: ListBreedsPresentationLogic?
    var worker: ListBreedsWorker?
    //var name: String = ""

    // MARK: Do something

    func initialLoad(request: ListBreeds.InitialLoad.Request) {
        worker = ListBreedsWorker()
        worker?.doSomeWork()

        let response = ListBreeds.InitialLoad.Response(breeds: [])
        presenter?.presentSomething(response: response)
    }
}
