//
//  DetailBreedPresenter.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBreedPresentationLogic {
    func presentPictures(response: DetailBreed.InitialLoad.Response)
}

class DetailBreedPresenter: DetailBreedPresentationLogic {
    weak var viewController: DetailBreedDisplayLogic?

    // MARK: Do something

    func presentPictures(response: DetailBreed.InitialLoad.Response) {
        let viewModel = DetailBreed.InitialLoad.ViewModel(pictures: response.pictures, title: response.title)
        viewController?.displayPictures(viewModel: viewModel)
    }
}
