//
//  DetailBreedInteractor.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBreedBusinessLogic {
    func initialLoad(request: DetailBreed.InitialLoad.Request)
}

protocol DetailBreedDataStore {
    var selectedBreed: String? { get set }
}

class DetailBreedInteractor: DetailBreedBusinessLogic, DetailBreedDataStore {
    var presenter: DetailBreedPresentationLogic?
    var worker: DetailBreedWorkerProtocol = DetailBreedWorker()
    var selectedBreed: String?

    // MARK: Do something

    func initialLoad(request: DetailBreed.InitialLoad.Request) {
        worker.listAllPictures(breedName: selectedBreed!, completion: { (apiResponse, error) in
            var response = DetailBreed.InitialLoad.Response(pictures: [], title: "Error Loading")
            if let apiResponse = apiResponse {
                response = DetailBreed.InitialLoad.Response(pictures: apiResponse.message, title: self.selectedBreed!)
            }
            self.presenter?.presentPictures(response: response)
        })

    }
}
