//
//  DetailBreedInteractor.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBreedBusinessLogic {
    func doSomething(request: DetailBreed.Something.Request)
}

protocol DetailBreedDataStore {
    //var name: String { get set }
}

class DetailBreedInteractor: DetailBreedBusinessLogic, DetailBreedDataStore {
    var presenter: DetailBreedPresentationLogic?
    var worker: DetailBreedWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: DetailBreed.Something.Request) {
        worker = DetailBreedWorker()
        worker?.doSomeWork()

        let response = DetailBreed.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
