//
//  DetailBreedWorker.swift
//  DogsApiCleanSwiftExample
//
//  Created by Santos Ramon on 10/10/18.
//  Copyright (c) 2018 Santos Ramon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBreedWorkerProtocol {
    func listAllPictures(breedName: String, completion: @escaping (BreedsApiResponseModel?, Error?) -> Void)
}

class DetailBreedWorker:DetailBreedWorkerProtocol {
    func listAllPictures(breedName: String, completion: @escaping (BreedsApiResponseModel?, Error?) -> Void) {
        BreedsAPI.shared.listAll(service: .listPictures(breed: breedName)) { (apiResponse, error) in
            completion(apiResponse, error)
        }
    }
}
